### ISSUE TITLE
react-native link break xcode

### ISSUE THREAD

**Issue by zorosun** [RobertSheaO/react-native-zendesk-support#18] opened 2017-11-14 17:19 UTC
after running `react-native link react-native-zendesk-support` command, I cannot open xcode project. I tried fixing project.pbxproj but still doesn't work...

**Comment by RobertSheaO** [comment] 2017-11-15 22:41
Please provide the version of React Native you're using

Does reverting the change, or running `react-native unlink react-native-zendesk-support` allow you to open your Xcode project?

What kind of error message is Xcode giving you? Please be more descriptive

**Comment by zorosun** [comment] 2017-11-17 06:38
I am using 

"react-native": "0.48.4",

`react-native link` is successful without error but once I opened xcode project, it will return error
"project.xcodeproj cannot be opened because the project file cannot be parsed."


So I ran `react-native unlink react-native-zendesk-support`, it said 
`
rnpm-install info Unlinking react-native-zendesk-support android dependency
rnpm-install info Android module react-native-zendesk-support has been successfully unlinked
rnpm-install ERR! It seems something went wrong while unlinking. Error: Expected "/*" or ";" but "\"" found.

Expected "/*" or ";" but "\"" found.
`

**Comment by RobertSheaO** [comment] 2017-11-17 06:47
It sounds like Xcode may have converted a file to XML. Can you verify the contents of `node_modules/react-native-zendesk-support/ios/RNZenDeskSupport.xcodeproj/project.pbxproj`? If it's XML and doesn't start with `// !$*UTF8*$!`, then you'll need to force Xcode to parse it correctly.

Here is how you do that:

Open `node_modules/react-native-zendesk-support/ios/RNZenDeskSupport.xcodeproj` in Xcode, make a change to any build setting, like switching a "No" to a "Yes" and then back to "No". This forces it into the correct format that React Native supports.

This is a common issue that arrises, especially with `react-native-fbsdk`. Let me know if this resolved the issue for you. It arrises when you use Cocoa Pods with a React Native project. You can read more about it here:

https://github.com/CocoaPods/CocoaPods/issues/1275#issuecomment-22391200

**Comment by zorosun** [comment] 2017-11-17 06:58
it does start with `// !$*UTF8*$!`, and I tried switching settings but still show the same result...

I'm using xcode `Version 9.0 (9A235)`

**Comment by RobertSheaO** [comment] 2017-11-17 07:35
Did you create your app using `create-react-native-app`?

**Comment by zorosun** [comment] 2017-11-17 07:53
No, I'm using https://github.com/futurice/pepperoni-app-kit template as a kick start but I will try create a new project using CRNA.

**Comment by RobertSheaO** [comment] 2017-11-17 07:53
I ask about CRNA, because a lot of people are having linking issues with it recently. Try following the manual linking steps to see if you're able to successfully install this module.

https://github.com/RobertSheaO/react-native-zendesk-support/blob/master/README.md#manually-linking-ios

**Comment by zorosun** [comment] 2017-11-17 07:56
Ok thank you, I didn't see manually linking-ios part in the README lol... I will let you know how it works out. 👍

**Comment by RobertSheaO** [comment] 2017-11-17 07:56
I just added it :)

**Comment by zorosun** [comment] 2017-11-17 07:57
Ohhh that's why hahah thx

**Comment by RobertSheaO** [comment] 2017-11-17 08:13
BTW, I downloaded `pepperoni-app-kit` and was able to link and unlink successfully, so it may be a conflict with a customization you've made, or another node package. If you continue to have this issue, please list your other linked libraries.

**Comment by zorosun** [comment] 2017-11-17 08:22
Thank you! I will check it out one by one :)

**Comment by RobertSheaO** [comment] 2017-11-20 22:33
Closing for now. If you identify the conflicting package or the root cause of your issue, please do reply back here.

**Closed by RobertSheaO** 2017-11-20 22:33 UTC
